<?php
require 'vendor/autoload.php'; // or require 'libs/dompdf/autoload.inc.php';

use Dompdf\Dompdf;

session_start();
include 'db.php';

if (!isset($_SESSION['admin_name'])) {
    exit("Unauthorized access.");
}

// Gather data
$totalPets = mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) AS count FROM pets"))['count'];
$availablePets = mysqli_fetch_assoc(mysqli_query($conn, "SELECT COUNT(*) AS count FROM pets WHERE pet_status = 'available'"))['count'];
$pendingApps = mysqli_fetch_assoc(mysqli_query($conn, "
  SELECT COUNT(*) AS count FROM adoptionapplications aa
  JOIN application_statuses s ON aa.status_id = s.status_id
  WHERE s.status_name = 'pending'
"))['count'];
$approvedApps = mysqli_fetch_assoc(mysqli_query($conn, "
  SELECT COUNT(*) AS count FROM adoptionapplications aa
  JOIN application_statuses s ON aa.status_id = s.status_id
  WHERE s.status_name = 'approved'
"))['count'];
$missingPets = mysqli_fetch_assoc(mysqli_query($conn, "
  SELECT COUNT(*) AS total FROM pets
  WHERE image_path IS NULL OR image_path = '' OR category_id IS NULL
  OR description IS NULL OR description = ''
"))['total'];
$newUsers = mysqli_fetch_assoc(mysqli_query($conn, "
  SELECT COUNT(*) AS total FROM users
  WHERE date_registered >= NOW() - INTERVAL 1 DAY
"))['total'];

$appsQuery = mysqli_query($conn, "
    SELECT 
        aa.application_id, u.fullname, u.email, u.phone_num,
        p.name AS pet_name, pc.category_name,
        s.status_name, aa.submission_date
    FROM adoptionapplications aa
    JOIN users u ON aa.user_id = u.user_id
    JOIN pets p ON aa.pet_id = p.pet_id
    LEFT JOIN pet_categories pc ON p.category_id = pc.category_id
    JOIN application_statuses s ON aa.status_id = s.status_id
    ORDER BY aa.submission_date DESC
");

// Create PDF content
$html = '
<h2 style="text-align:center;">Pawfect Home Admin Dashboard Report</h2>
<p><strong>Generated by:</strong> ' . htmlspecialchars($_SESSION['admin_name']) . '</p>
<p><strong>Date:</strong> ' . date("F j, Y, g:i a") . '</p>
<hr>
<h3>Summary</h3>
<ul>
  <li>Total Pets: ' . $totalPets . '</li>
  <li>Available Pets: ' . $availablePets . '</li>
  <li>Pending Applications: ' . $pendingApps . '</li>
  <li>Approved Applications: ' . $approvedApps . '</li>
  <li>Pets Missing Info: ' . $missingPets . '</li>
  <li>New Users (Last 24 hrs): ' . $newUsers . '</li>
</ul>

<h3>Recent Applications</h3>
<table border="1" cellpadding="5" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Applicant</th>
      <th>Pet</th>
      <th>Category</th>
      <th>Status</th>
      <th>Submitted</th>
    </tr>
  </thead>
  <tbody>';

while ($row = mysqli_fetch_assoc($appsQuery)) {
    $html .= '<tr>
      <td>' . htmlspecialchars($row['fullname']) . '</td>
      <td>' . htmlspecialchars($row['pet_name']) . '</td>
      <td>' . htmlspecialchars($row['category_name']) . '</td>
      <td>' . ucfirst(htmlspecialchars($row['status_name'])) . '</td>
      <td>' . date('M d, Y — h:i A', strtotime($row['submission_date'])) . '</td>
    </tr>';
}

$html .= '</tbody></table>';

// Generate PDF
$dompdf = new Dompdf();
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();
$dompdf->stream("Dashboard_Report_" . date("Ymd") . ".pdf", ["Attachment" => true]);
exit;
